# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learning_nbdev',
                'doc_host': 'https://chandangm.github.io',
                'git_url': 'https://github.com/chandangm/learning_nbdev',
                'lib_path': 'learning_nbdev'},
  'syms': {'learning_nbdev.core': {'learning_nbdev.core.foo': ('core.html#foo', 'learning_nbdev/core.py')}}}
